package com.octal.actorPay.dto.enums;

public enum NotificationTypeEnum {

    SIGN_UP("SIGN_UP"),
    WITHDRAW("WITHDRAW"),
    REQUEST_MONEY("REQUEST_MONEY"),
    ADD_MONEY("ADD_MONEY"),
    ORDER_PLACE("ORDER_PLACE"),
    ORDER_NOTE("ORDER_NOTE"),
    ORDER_RECEIVED("ORDER_RECEIVED"),
    CANCEL_ORDER("CANCEL_ORDER"),
    RETURN_ORDER("RETURN_ORDER"),
    RETURN_REQUEST("RETURN_REQUEST"),


    ADD_MONEY_TO_WALLET("ADD_MONEY_TO_WALLET"),
    WITHDRAW_MONEY_FROM_WALLET("WITHDRAW_MONEY_FROM_WALLET"),
    UTILITY_PAYMENT("UTILITY_PAYMENT"),
    CREDIT_INTO_WALLET("CREDIT_INTO_WALLET"),
    DEBIT_FROM_WALLET("DEBIT_FROM_WALLET"),
    ONLINE_SHOPPING_PAYMENT("ONLINE_SHOPPING_PAYMENT"),
    ORDER_STATUS_CHANGE("ORDER_STATUS_CHANGE"),
    RETURNING_DECLINED("RETURNING_DECLINED"),
    RETURNED("RETURNED"),
    RETURNING_ACCEPTED("RETURNING_ACCEPTED"),
    ORDER_DELIVERED("ORDER_DELIVERED"),
    USER_APPLIED_OF_CANCEL("USER_APPLIED_OF_CANCEL"),
    NEW_MESSAGE("NEW_MESSAGE"),
    WRONG_PIN("WRONG_PIN"),
    POINTS_REDEEM("POINTS_REDEEM"),
    REFERRAL_BONUS("REFERRAL_BONUS"),
    LOW_BALANCE("LOW_BALANCE"),
    REMINDER_OF_BILL_PAYMENT("REMINDER_OF_BILL_PAYMENT");

    private String status;

    private NotificationTypeEnum(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return status;
    }
}
