package com.octal.actorPay.constants;

public enum OrderStatus {

    SUCCESS,
    READY,
    DISPATCHED,
    CANCELLED,
    PARTIALLY_CANCELLED,
    RETURNING,
    PARTIALLY_RETURNING,
    RETURNED,
    PARTIALLY_RETURNED,
    PENDING,
    FAILED,
    DELIVERED,
    RETURNING_ACCEPTED,
    RETURNING_DECLINED,
    PARTIALLY_RETURNING_ACCEPTED,
    PARTIALLY_RETURNING_DECLINED,
    HOLD
}
