server:
  port: 8083
  error:
    include-stacktrace: never

spring:

  application:
    name: admin-service


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #  datasource:
  #    url: jdbc:mariadb://rds-mumsdbserv01.c3j6kksosxgk.ap-south-1.rds.amazonaws.com:3306/actorApp
  #    username: admin
  #    password: MariaDBPassword
  #    driver-class-name: org.mariadb.jdbc.Driver


  #Live Server
#  datasource:
#    url: jdbc:mariadb://actorpay2.c3j6kksosxgk.ap-south-1.rds.amazonaws.com:3306/actor_pay_admin_db
#    username: actorpay
#    password: Actorpay#!15
#    driver-class-name: org.mariadb.jdbc.Driver

  #Local Server
  datasource:
    url: jdbc:mariadb://localhost:3307/actor_pay_admin_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
#    initialize: true

defaultZone: http://localhost:8761
registerWithEureka: true

#Swagger-ui Settings
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operationsSorter: alpha
    enabled: true
  pathsToMatch: /*/**
  packagesToScan: com.octal.actorPay.controller
  show-actuator: true



#JWT token properties, token validity in seconds
jwt:
  access:
    token:
      validity: 60000
  refresh:
    token:
      validity: 20000
  secret: actorPay



forgot.password.time.in.second: 60
forgot.password.otp.resend.count: 3
user.activation.link.url: http://i.actorypay.com:7070/?token=<token>
user.forget.password.link: http://192.168.1.114:2022/reset-password/<token>

S3Upload:
  access-key: AKIA6NDTRQRBFMUF77JO
  secret-key: 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
S3base:
  url: https://s3-sbucket1.s3.ap-south-1.amazonaws.com/
external.sms.service.url: https://platform.clickatell.com/messages