CREATE TABLE user_document (
id varchar(255) NOT NULL,
created_at datetime DEFAULT NULL,
is_deleted tinyint(1) DEFAULT 0,
is_active bit(1) DEFAULT NULL,
updated_at datetime DEFAULT NULL,
doc_type varchar(255) DEFAULT NULL,
document_data longtext DEFAULT NULL,
verified_status varchar(15) DEFAULT NULL,
user_id varchar(255) DEFAULT NULL,
id_no varchar(255) DEFAULT NULL,
reason_description varchar(500) DEFAULT NULL,
PRIMARY KEY (id),
KEY user_fk_user_doc (user_id),
CONSTRAINT user_fk_user_doc FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE users (
id varchar(255) NOT NULL,
created_at datetime DEFAULT NULL,
is_deleted tinyint(1) DEFAULT 0,
is_active bit(1) DEFAULT NULL,
updated_at datetime DEFAULT NULL,
aadhar_number varchar(255) DEFAULT NULL,
contact_number varchar(255) DEFAULT NULL,
date_of_birth date DEFAULT NULL,
email varchar(255) NOT NULL,
is_email_verified bit(1) DEFAULT NULL,
extension_number varchar(255) DEFAULT NULL,
facebook_id varchar(255) DEFAULT NULL,
fcm_token varchar(255) DEFAULT NULL,
first_name varchar(255) DEFAULT NULL,
gender varchar(255) DEFAULT NULL,
google_id varchar(255) DEFAULT NULL,
invalid_login_attempts int(11) DEFAULT NULL,
kyc_status varchar(20) DEFAULT NULL,
is_notification_active bit(1) DEFAULT NULL,
last_login datetime DEFAULT NULL,
last_name varchar(255) DEFAULT NULL,
login_type varchar(255) DEFAULT NULL,
pan_number varchar(255) DEFAULT NULL,
password varchar(255) DEFAULT NULL,
is_phone_verified bit(1) DEFAULT NULL,
profile_picture_url varchar(255) DEFAULT NULL,
twitter_id varchar(255) DEFAULT NULL,
upi_qr_code varchar(255) DEFAULT NULL,
user_type varchar(255) DEFAULT NULL,
user_name varchar(255) DEFAULT NULL,
role_id varchar(255) DEFAULT NULL,
PRIMARY KEY (id),
UNIQUE KEY unique_email (email),
UNIQUE KEY aadhar_number_UNIQUE (aadhar_number),
UNIQUE KEY pan_number_UNIQUE (pan_number),
KEY FK_user_role (role_id),
CONSTRAINT FK_user_role FOREIGN KEY (role_id) REFERENCES role (id)
);
