spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #  datasource:
  #    url: jdbc:mariadb://rds-mumsdbserv01.c3j6kksosxgk.ap-south-1.rds.amazonaws.com:3306/actorApp
  #    username: admin
  #    password: MariaDBPassword
  #    driver-class-name: org.mariadb.jdbc.Driver


#Live Server
#  datasource:
#    url: jdbc:mariadb://actor-pay.c3j6kksosxgk.ap-south-1.rds.amazonaws.com:3306/actorApp
#    username: actorpay
#    password: Actorpay#!15
#    driver-class-name: org.mariadb.jdbc.Driver

#Local Server
  datasource:
    url: jdbc:mariadb://localhost:3307/actorApp
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
