server:
  port: 8090
  error:
    include-stacktrace: never

spring:
  application:
    name: chat-service
  profiles:
    active: development
#  cloud:
#    config:
#      uri:  http://localhost:8888
#      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


#Local Server
  datasource:
    url: jdbc:mariadb://localhost:3306/actor_pay_chat_service_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

#JWT token properties, token validity in seconds
jwt:
    access:
        token:
            validity: 60000
    refresh:
        token:
            validity: 20000
    secret: actorPay

defaultZone:  http://localhost:8761
registerWithEureka: true


## value in hours
user.phone.verification.otp.expire: 1

## user max invalid credential attempts
user.max.invalid.password.count:  5


S3Upload:
  access-key: AKIA6NDTRQRBFMUF77JO
  secret-key: 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
S3base:
  url: https://s3-sbucket1.s3.ap-south-1.amazonaws.com/
external.sms.service.url: https://platform.clickatell.com/messages
